#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define PRESS_DELAY 100000			// delay in uS
#define REST_DELAY 20000 	//delay in uS
#define STYLUS_CLICK_POSITION 73
#define STYLUS_REST_POSITION 90
#define PWM_PIN 1


#define PWM_RANGE 2000
#define PWM_CLOCK 192
#define MIN_PWM_PULSE_DURATION 80
#define MAX_PWM_PULSE_DURATION 200


#endif //CONFIGURATION_H
