#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define PRESS_DELAY 100
#define DELAY 450 - PRESS_DELAY


#define PWM_RANGE 2000
#define PWM_CLOCK 192
#define MIN_PWM_PULSE_DURATION 100
#define MAX_PWM_PULSE_DURATION 200
#define STYLUS_TOUCH_POSITION 140
#define STYLUS_REST_POSITION 155

#endif //CONFIGURATION_H
